Iter13
Jackalgit/BuildShortURL pull request #17
Opened 2024-01-21 21:24 UTC by Jackalgit

2024-01-25 15:43 UTC, bambruysk requested changes
Нужно чуть доработать

2024-01-25 15:43 UTC, bambruysk commented on cmd/config/config.go
> +	//	`localhost`, `5432`, `shorturl`)
Для подключения БД в тестах лучше создать отдельный конструктор конфигов в тесте 

Именно поэтому ( но не только) поэтому использование глобальных переменных плохо

Обычно мы собираем все конфиги приложения в одну структуру, экземпляр котолрой получается каким-то образовм из вне или просто создается в тестах

2024-01-25 15:43 UTC, bambruysk commented on cmd/shortener/main.go
> +	//)
А чего эти удалили?

2024-01-25 15:43 UTC, bambruysk commented on internal/database/db.go
> +	ctx, cancel := context.WithTimeout(ctx, 1*time.Second)
Лучше задавать этот параметр из конфига

2024-01-25 15:43 UTC, bambruysk commented on internal/database/db.go
> +	db, err := sql.Open("pgx", config.Config.DatabaseDSN)
можно сохрагнить это подключение в DataBase и переиспользовать, чтобы не создавать его каждый раз при каждом запросе

2024-01-25 15:43 UTC, bambruysk commented on internal/database/db.go
> +			dupShortURLKey := GetShortURLinDB(ctx, originalURL)
Лишний поход в базу - можно было бы получить за один запрос

2024-01-25 15:43 UTC, bambruysk commented on internal/handlers/handlers.go
Лучше однократно сделать выбор на этапе конфигурирования и выбрать нужное хранилище

2024-01-25 15:43 UTC, bambruysk commented on internal/database/db.go
> +func GetShortURLinDB(ctx context.Context, originalURL []byte) string {
жто тоже же можно методомо сделать

2024-01-25 17:15 UTC, Jackalgit commented on cmd/shortener/main.go
> +	//)
Тесты зависали на первом же и не двигались.

2024-01-25 17:50 UTC, Jackalgit commented on cmd/config/config.go
> +	//	`localhost`, `5432`, `shorturl`)
В данном случаи тесты "ручные"
Про общий конфиг структуру понятно, мне не понятны тесты на инкременты точнее рамки за которые я могу выходить при написании приложения. По этому делаю по теории и заданию. Если я не правильно понял замечание то поясните как создать такой конфиг и не поломать прохождение тестов.

2024-01-25 17:51 UTC, Jackalgit commented on internal/database/db.go
> +	ctx, cancel := context.WithTimeout(ctx, 1*time.Second)
Какой параметр?

2024-01-25 17:52 UTC, Jackalgit commented on internal/database/db.go
> +	db, err := sql.Open("pgx", config.Config.DatabaseDSN)
Насколько хорошо оставлять висящие подключение к ДБ? В мое случае я подключился, создал таблицу, закрыл соединение с ДБ.

2024-01-25 17:54 UTC, Jackalgit commented on internal/handlers/handlers.go
Не понимаю как это сделать не сломав тесты инкрементов.

2024-01-25 18:35 UTC, Jackalgit commented on internal/database/db.go
> +			dupShortURLKey := GetShortURLinDB(ctx, originalURL)
Не понимаю как написать такой запрос вставки в ДБ чтоб в случае задваивания оригинального урл возвращался бы уже его сохраненный короткий урл? В задании было предложено 2 варианта реализации я воспользовался одним из них. 

Я так понимаю речь про запрос вида:
query := `INSERT INTO storage (shortURLKey, originalURL) VALUES($1, $2) ON CONFLICT (originalURL) RETURNING shortURLKey`

2024-01-25 18:42 UTC, Jackalgit commented on internal/database/db.go
> +func GetShortURLinDB(ctx context.Context, originalURL []byte) string {
Если в структуру ДБ не сохранять подключение к ДБ то зачем эту функцию делать как метод? К тому же необходимо будет возвращать в хендлер оригинальный урл.

2024-01-26 17:45 UTC, Jackalgit commented on internal/handlers/handlers.go
У нас выбор или ДБ или Память + Файл

2024-01-26 18:27 UTC, Jackalgit commented on internal/database/db.go
> +	db, err := sql.Open("pgx", config.Config.DatabaseDSN)
исправлено

2024-01-26 18:27 UTC, Jackalgit commented on internal/database/db.go
> +func GetShortURLinDB(ctx context.Context, originalURL []byte) string {
исправлено

2024-01-26 18:28 UTC, Jackalgit commented on cmd/config/config.go
> +	//	`localhost`, `5432`, `shorturl`)
удалено

2024-01-29 18:25 UTC, bambruysk commented on internal/database/db.go
> +	ctx, cancel := context.WithTimeout(ctx, 1*time.Second)
Таймаут соединения

2024-01-29 18:30 UTC, bambruysk requested changes
Нужно сделать выбор хранилища на этапе конфигурации через паттерн Repossitory

2024-01-29 18:30 UTC, bambruysk commented on internal/handlers/handlers.go
Да - флаг задается при старте приложения. Конфигурацию можно считать статичной. 
Тогда мы можем однократно выбрать необходимое хранлище и проснуть сюда через interface

2024-02-02 12:37 UTC, bambruysk approved these changes
Принято

2024-02-09 19:11 UTC, merged