Iter15
Jackalgit/BuildShortURL pull request #19
Opened 2024-02-03 05:36 UTC by Jackalgit

2024-02-05 14:58 UTC, bambruysk requested changes
Нужно доработать

2024-02-05 14:58 UTC, bambruysk commented on internal/database/db.go
> +		log.Printf("[PrepareContext] %s", err)
Тут надо бы ошибку вернуть - иначе паника  или некореектное поведение может быть может быть

2024-02-05 14:58 UTC, bambruysk commented on internal/database/db.go
> +		}
здесь return err пропущен

2024-02-05 14:58 UTC, bambruysk commented on internal/database/db.go
> +	}
здесь тоже return пропущен

2024-02-05 14:58 UTC, bambruysk commented on internal/database/db.go
> +func (d DataBase) GetURL(ctx context.Context, userID uuid.UUID, shortURLKey string) ([]byte, bool, bool) {
Лучше возвращать ошибку вместо набора флагов

2024-02-05 14:58 UTC, bambruysk commented on internal/database/db.go
> +		log.Printf("Ошибка начала транзакции: %q", err)
здесь стоит вернуть ошибку и не продолжать работу

2024-02-05 14:58 UTC, bambruysk commented on internal/database/db.go
> +		log.Printf("[PrepareContext] %s", err)
здесь нужно вернуть ошибку ( и не забыть tx.Rollback() - но его можно в defer

2024-02-05 14:58 UTC, bambruysk commented on internal/database/db.go
> +			}
здесь тоже нужно вернуть ошибку

2024-02-05 14:58 UTC, bambruysk commented on internal/database/db.go
> +		}
Здесь тоже....

2024-02-05 14:58 UTC, bambruysk commented on internal/database/db.go
> +		log.Printf("[row Scan] Не удалось преобразовать данные: %q", err)
return

2024-02-05 14:58 UTC, bambruysk commented on internal/database/db.go
> +	}
return

2024-02-05 14:58 UTC, bambruysk commented on internal/database/db.go
> +			log.Printf("[rows Scan] Не удалось преобразовать данные: %q", err)
В общем везде нужно возвращать ошибку

2024-02-05 14:58 UTC, bambruysk commented on internal/database/db.go
> +func (d DataBase) UserURLList(ctx context.Context, userID uuid.UUID) ([]models.ResponseUserURL, bool) {
научить функцию возвращать ошибку

2024-02-05 14:58 UTC, bambruysk commented on internal/database/db.go
> +
почему бы не использовать существуюбщее в  Database соединение?

2024-02-05 14:58 UTC, bambruysk commented on internal/initialization/init.go
> +			Ctx:             ctx,
не надо хранить контекст в структурах - это не имеет смысла, так как контекст распространяется либо в рамках запроса, либо в рамках приложения. Если хочется смотреть на контекст приложения то лучше захватить его в методе запуска 

https://pkg.go.dev/context

Do not store Contexts inside a struct type; instead, pass a Context explicitly to each function that needs it.

2024-02-05 14:58 UTC, bambruysk commented on internal/handlers/handlers.go
> +	if err := s.Storage.AddURL(s.Ctx, userID, shortURLKeyFull, originalURL); err != nil {
контекст нужно взять из запроса r.Context()

2024-02-05 14:58 UTC, bambruysk commented on internal/handlers/handlers.go
> +	if err == http.ErrNoCookie {
всегда лучше проверять через errors.Is

2024-02-05 14:58 UTC, bambruysk commented on internal/jobertask/jober_task.go
> +	Ctx      context.Context
Не надо хранить контекст в структуре

2024-02-05 14:58 UTC, bambruysk commented on internal/jobertask/jober_task.go
> +func Worker(ctx context.Context, wg *sync.WaitGroup, doneCh chan struct{}, userID uuid.UUID, inputCh chan string) {
Хорошо придумано с воркерами но есть минус, у нас каждый воркер запускается по каждому пользователю. То есть я например отправляю запрос на удаление 50 урлов, размера батча 100 - и я буду ждать очень долго ( пока сервер не перегрузится) когда же они удалятся.  Кроме того. множество таких запросов могут сожрать всю память

то есть стоит добавить тикер, и с определнным интервалом делать удаление.

Вообще чтобы совсем красиво было, стоит добавить возможность удалять батчи содержащие пары url, user -  тогда можно запросы всех пользователей сливать в один канал, оттуда формировать батч и отправлять в БД

2024-02-05 14:58 UTC, bambruysk commented on internal/jobertask/jober_task.go
> +		Worker(ctx, wg, doneCh, userID, inputCh)
В дополнение в следующему комменту. Рассмотрим следующую ситуацию -  у меня 30 урлов, размер батча 20 воркеров 3. Каждый воркер съест в среднем по 10 урлов и будет ждать еще 10 чтобы завершиться

То есть чтобы схема эффективно работала с базой - нужно научить воркеры работать с разными userID

2024-02-05 14:58 UTC, bambruysk commented on internal/util/build_token.go
> +package util
наличе такого пакета - обычно говорит о так себе архитектуре https://dave.cheney.net/2019/01/08/avoid-package-names-like-base-util-or-common 

Лучше разделить на три пакета с разными назначением и конкретно проименовать например jwt, итд

2024-02-05 14:58 UTC, bambruysk commented on internal/handlers/handlers.go
> +		log.Println("[GetURL] Token is not valid", err)
return?

2024-02-05 17:57 UTC, Jackalgit commented on internal/database/db.go
> +
Думал на этот счет. Но
1. Удаление урлов из базы есть только для Базы данных и придется делать метод заглушку для варианта когда сохраняем урлы в памяти, чтоб соответствовать интерфейсу.
2. Нужно будет "тащить"  экземпляр хранилища сквозь "воркеры", чтоб датащить conn *sql.DB до функции работы с базой.
3.  Бороться с циклическими зависимостями.
4. В хендлер добавлять что то типа if config.Config.DatabaseDSN == "" {.......  }, чтоб в случае если выбрано INmemory "случайно" не дернули ручку "/api/user/urls"

2024-02-05 17:59 UTC, Jackalgit commented on internal/database/db.go
> +
Все это вроде как можно решить, но выглядит не уместно в рамках данного учебного проекта

2024-02-07 15:13 UTC, bambruysk approved these changes
Принято

2024-02-09 19:11 UTC, merged